server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    datasource:
      platform: postgres
    hibernate:
      ddl-auto: update

admin:
  email: admin@mail.com
  password: admin123